In [ ]:
!pip install gensim

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king=wv['king']

In [ ]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
wv.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [ ]:
vec_cricket=wv['cricket']

In [ ]:
wv.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
import pandas as pd

In [ ]:
data={
    "text":[
         "Breaking news: Government announces tax relief for small businesses",
        "Click here to win a free iPhone now!",
        "NASA discovers water on Mars in groundbreaking research",
        "Exclusive: Celebrity spotted at local restaurant!",
        "Breaking: Huge discount on electronics for the next 24 hours",
        "World Health Organization advises wearing masks to prevent virus spread",
        "You won't believe this one weird trick to lose weight fast!",
        "Scientists discover a new species of butterfly in the Amazon",
        "This is the ultimate guide to making money overnight!",
        "Experts predict an increase in global temperatures next year",
        "Get rich quick with this new crypto scheme",
        "Researchers develop a new treatment for cancer",
        "Politicians caught in a scandalous debate over climate change",
        "Start your day with this amazing energy drink offer!",
        "Doctors recommend regular exercise for better health",
        "Free gifts for the first 100 customers only!",
        "Economists warn about an impending recession in global markets",
        "Win a luxury vacation to Paris by entering this contest!",
        "Tech companies announce a new breakthrough in AI technology",
        "Congratulations! You've won a $1000 gift card. Claim now!",
    ],
    "label":[
              "real", "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real",
        "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real", "fake"
    ]
}
df=pd.DataFrame(data)

In [ ]:
df

text label
0   Breaking news: Government announces tax relief...  real
1                Click here to win a free iPhone now!  fake
2   NASA discovers water on Mars in groundbreaking...  real
3   Exclusive: Celebrity spotted at local restaurant!  real
4   Breaking: Huge discount on electronics for the...  fake
5   World Health Organization advises wearing mask...  real
6   You won't believe this one weird trick to lose...  fake
7   Scientists discover a new species of butterfly...  real
8   This is the ultimate guide to making money ove...  fake
9   Experts predict an increase in global temperat...  real
10         Get rich quick with this new crypto scheme  fake
11     Researchers develop a new treatment for cancer  real
12  Politicians caught in a scandalous debate over...  real
13  Start your day with this amazing energy drink ...  fake
14  Doctors recommend regular exercise for better ...  real
15       Free gifts for the first 100 customers only!  fake
16  Economists warn about an impending recession i...  real
17  Win a luxury vacation to Paris by entering thi...  fake
18  Tech companies announce a new breakthrough in ...  real
19  Congratulations! You've won a $1000 gift card....  fake

In [ ]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
df['label']=df['label'].map({"fake":0,"real":1})
df['label']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: label, dtype: float64

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
stop_words=set(stopwords.words("english"))

In [ ]:
def preprocess_text(text):
  text=text.lower()
  tokens=text.split()
  tokens=[word for word in tokens if word not in stop_words]
  tokens=[lemmatizer.lemmatize(word) for word in tokens]
  return " ".join(tokens)
df['text']=df['text'].apply(preprocess_text)

In [ ]:
df.head()

text  label
0  breaking news: government announces tax relief...    NaN
1                         click win free iphone now!    NaN
2   nasa discovers water mar groundbreaking research    NaN
3     exclusive: celebrity spotted local restaurant!    NaN
4   breaking: huge discount electronics next 24 hour    NaN

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['label'],test_size=0.1,random_state=42)

In [ ]:
print(X_train.shape)

(18,)


In [ ]:
X_test.shape

(2,)

In [ ]:
y_train.value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
y_test.value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [ ]:
X_train_vectorized=vectorizer.fit(X_train)

In [ ]:
X_train_vectorized=vectorizer.transform(X_train)

In [ ]:
X_test_vectorized=vectorizer.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_model=MultinomialNB()

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
X_train = ["This is a test", "NaN", None, "Another example", " "]
y_train = [1, None, 0, 1, None]
X_train = pd.Series(X_train)
y_train = pd.Series(y_train)
cleaned_data = pd.concat([X_train, y_train], axis=1).dropna()
X_train = cleaned_data[0]
y_train = cleaned_data[1]
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)


MultinomialNB()

In [ ]:
y_train_pred=nb_model.predict(X_train_vectorized)

In [ ]:
list(y_train)

[1.0, 1.0]

In [ ]:
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
accuracy_score(y_train,y_train_pred)

1.0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)
y_test_pred = nb_model.predict(X_test_vectorized)


In [ ]:
accuracy_score(y_test,y_test_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/_array_api.py:390: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)


ValueError: Input y_true contains NaN.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Vectorize the text
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# Train the Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)

# Predict on the test set
y_test_pred = nb_model.predict(X_test_vectorized)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy)


ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by MultinomialNB.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.1, random_state=42)

# Check if any dataset is empty
print("Length of X_train:", len(X_train))
print("Length of X_test:", len(X_test))
print("Length of y_train:", len(y_train))
print("Length of y_test:", len(y_test))

# Vectorize the text
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# Check shapes after vectorization
print("Shape of X_train_vectorized:", X_train_vectorized.shape)
print("Shape of X_test_vectorized:", X_test_vectorized.shape)

# Train the Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)

# Predict on the test set
y_test_pred = nb_model.predict(X_test_vectorized)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy)


Length of X_train: 18
Length of X_test: 2
Length of y_train: 18
Length of y_test: 2
Shape of X_train_vectorized: (18, 102)
Shape of X_test_vectorized: (2, 102)


ValueError: Input y contains NaN.

In [ ]:
# Check for NaN values in y_train
print("NaN values in y_train:", y_train.isna().sum())

# Remove rows with NaN values from both X_train and y_train
valid_indices = ~y_train.isna()
X_train = X_train[valid_indices]
y_train = y_train[valid_indices]

# Re-vectorize X_train after removing NaNs
X_train_vectorized = vectorizer.fit_transform(X_train)

# Train the Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)

# Predict on the test set
y_test_pred = nb_model.predict(X_test_vectorized)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy)


NaN values in y_train: 18


ValueError: empty vocabulary; perhaps the documents only contain stop words

In [ ]:
# Check if X_train is empty after filtering NaN values from y_train
print("Length of X_train:", len(X_train))
print("Sample of X_train:", X_train.head())

# If X_train is empty, handle this case
if X_train.empty:
    print("X_train contains no valid data after filtering.")
else:
    # Re-vectorize X_train
    X_train_vectorized = vectorizer.fit_transform(X_train)

    # Train the Naive Bayes model
    nb_model = MultinomialNB()
    nb_model.fit(X_train_vectorized, y_train)

    # Predict on the test set
    y_test_pred = nb_model.predict(X_test_vectorized)

    # Calculate accuracy score
    accuracy = accuracy_score(y_test, y_test_pred)
    print("Accuracy:", accuracy)


Length of X_train: 0
Sample of X_train: Series([], Name: text, dtype: object)
X_train contains no valid data after filtering.


In [ ]:
y_test,y_test_pred

(0    NaN
 17   NaN
 Name: label, dtype: float64,
 array([1., 1.]))

In [ ]:
report=classification_report(y_test,y_test_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [ ]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
param_grid={

            "C":[0.1,0.3,0.5,1,10],
            "kernel":["linear","rbf"],
            "gamma":['scale',"auto"]
}

svm_model=SVC(random_state=42)

In [ ]:
grid_search=GridSearchCV(svm_model,param_grid,cv=5,scoring="accuracy")

In [ ]:
grid_search.fit(X_train_vectorized,y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [0.1, 0.3, 0.5, 1, 10],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [ ]:
grid_search.best_params_

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}

In [ ]:
grid_search.best_score_

0.6333333333333332

In [ ]:
best_model=grid_search.best_estimator_

In [ ]:
y_pred=best_model.predict(X_test_vectorized)

In [ ]:
report=classification_report(y_test,y_test_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [ ]:
accuracy_score(y_test,y_test_pred)

0.75

In [ ]:
data={
    "Title": [
        "Breaking news: COVID-19 vaccine is a scam!",
        "NASA discovers new planet with signs of life",
        "Fake celebrity dies in car crash story circulates",
        "New study confirms coffee boosts productivity"
    ],
    "Label": [1, 0, 1, 0]  # 1 = Fake, 0 = Real
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer(max_features=50)

In [ ]:
X=tfidf.fit_transform(df['Title']).toarray()
y=df['Label']

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

In [ ]:
model=Sequential([Dense(64,activation='relu',input_shape=(X.shape[1],)),
                  Dropout(0.5),
                  Dense(32,activation="relu"),
                  Dense(1,activation="sigmoid")

                  ])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer=Adam(learning_rate=0.001),
              loss=BinaryCrossentropy(),
              metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2500 - loss: 0.7091
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6831
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.7500 - loss: 0.6918
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.5000 - loss: 0.6765
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 1.0000 - loss: 0.6277
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.6365
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.6523
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.2500 - loss: 0.7060


In [ ]:
loss,accuracy=model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6574


In [ ]:
loss,accuracy

(0.6574366688728333, 1.0)

In [ ]:
model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[0.5309954 ],
       [0.48239043],
       [0.5163971 ],
       [0.49202934]], dtype=float32)

In [ ]:
y

0    1
1    0
2    1
3    0
Name: Label, dtype: int64

In [ ]:
!pip install faker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 13.3 MB/s eta 0:00:00


In [ ]:
from faker import Faker

In [ ]:
import numpy as np

In [ ]:
fake=Faker()
Faker.seed(42)

In [ ]:
def generate_text_labels(num_samples=5000):
    text=[fake.sentence(nb_words=10) for i in range(num_samples)]
    labels=np.random.randint(0,2,num_samples)
    return text,labels

In [ ]:
texts,labels=generate_text_labels()

In [ ]:
texts

['Agent every development say quality throughout beautiful.',
 'All behavior discussion own night respond red information last everything thank.',
 'Recently future choice whatever from behavior benefit suggest.',
 'Enough analysis least by two bad fall pick those gun court attorney product.',
 'World talk term herself law street class great prove.',
 'Participant commercial rock clear here writer.',
 'Detail food shoulder argue start source husband at tree note responsibility defense material.',
 'Central cause seat much section investment on gun young catch management.',
 'Technology check civil quite others his.',
 'You more wife team activity result race Mr environment political born itself law.',
 'Will seven medical blood personal success medical current hear.',
 'Much single morning a food affect upon these.',
 'Dream drive note bad rule staff within mouth call.',
 'Water close month parent who up sense ready require human public health.',
 'Later easy ask again network open acc

In [ ]:
labels

array([1, 1, 0, ..., 0, 0, 1])

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer=Tokenizer(num_words=10000)

In [ ]:
sequences=tokenizer.texts_to_sequences(texts)

In [ ]:
sequences

[[738, 228, 739, 821, 378, 191, 650],
 [330, 29, 379, 487, 192, 782, 229, 740, 282, 42, 822],
 [230, 30, 331, 117, 741, 29, 231, 22],
 [651, 91, 283, 590, 284, 118, 285, 652, 119, 120, 783, 784, 332],
 [424, 193, 23, 425, 16, 43, 785, 426, 742],
 [333, 956, 286, 121, 334, 743],
 [957, 696, 92, 335, 653, 75, 122, 427, 428, 76, 591, 232, 194],
 [592, 233, 915, 697, 336, 593, 698, 120, 429, 123, 699],
 [744, 870, 700, 195, 337, 338],
 [5, 60, 44, 594, 339, 234, 488, 287, 288, 31, 654, 289, 16],
 [538, 430, 340, 61, 290, 235, 340, 952, 786],
 [697, 45, 964, 431, 696, 871, 936, 432],
 [380, 291, 76, 118, 823, 787, 152, 539, 341],
 [46, 655, 489, 32, 656, 196, 24, 197, 342, 788, 153, 236],
 [490, 491, 492, 62, 595, 824, 343, 745, 237, 2, 330, 596],
 [540, 292, 238, 433, 825, 124, 344, 541, 542, 77, 434, 381],
 [154, 78, 8, 701, 493, 382, 286, 345, 597, 783, 890],
 [33, 42, 63, 746, 383, 744, 93],
 [543, 155, 916, 29, 747, 702],
 [494, 657, 122, 198, 598, 424, 435, 541, 293, 294, 117],
 [332,

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
padded_sequences=pad_sequences(sequences,maxlen=20)

In [ ]:
padded_sequences[0:2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        738, 228, 739, 821, 378, 191, 650],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 330,  29, 379, 487,
        192, 782, 229, 740, 282,  42, 822]], dtype=int32)

In [ ]:
X_train,X_test=padded_sequences[:train_size],padded_sequences[train_size:]

In [ ]:
X_train.shape

(4000, 20)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN,Dense

In [ ]:
model_one_to_one=Sequential([
                             Embedding(input_dim=5000,output_dim=64,input_length=20),
                             SimpleRNN(64,return_sequences=False),
                             Dense(1,activation="softmax")
                             ])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model_one_to_one.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
model_one_to_one.fit(X_train,y_train,epochs=5,batch_size=32,validation_split=0.2)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


100/100 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - accuracy: 0.5154 - loss: 0.6943 - val_accuracy: 0.4412 - val_loss: 0.7009
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.4959 - loss: 0.5855 - val_accuracy: 0.4412 - val_loss: 0.7976
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.4916 - loss: 0.2788 - val_accuracy: 0.4412 - val_loss: 1.1514
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.5051 - loss: 0.0912 - val_accuracy: 0.4412 - val_loss: 1.8381
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.4966 - loss: 0.0239 - val_accuracy: 0.4412 - val_loss: 2.1037


In [ ]:
model_one_to_one.predict(X_test)

 1/32 ━━━━━━━━━━━━━━━━━━━━ 10s 347ms/step

/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step


/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


array([[0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.999

In [ ]:
model_one_to_many=Sequential([
                             Embedding(input_dim=5000,output_dim=64,input_length=1),
                             SimpleRNN(64,return_sequences=True),
                             Dense(5000,activation="softmax")
                             ])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
X_gen=np.random.randint(1,5000,size=(5000,1))
y_gen=np.random.randint(1,5000,size=(5000,10))

In [ ]:
X_gen.shape

(5000, 1)

In [ ]:
y_gen.shape

(5000, 10)

In [ ]:
y_gen

array([[1999, 2564, 4435, ...,  658, 4498, 1938],
       [3353, 3242, 1902, ..., 1094, 2857, 2992],
       [ 732,  920, 1753, ..., 1310,  557, 2089],
       ...,
       [1300, 1749, 2522, ..., 2742, 2491, 4575],
       [3562, 3147, 1336, ..., 3898, 2386, 2453],
       [1479,  634, 3329, ..., 4015, 3430, 3095]])

In [ ]:
sequence_length = 10
X_gen = np.random.randint(1, 5000, size=(5000, sequence_length))
y_gen = np.random.randint(1, 5000, size=(5000, sequence_length))

model_one_to_many = Sequential([
    Embedding(input_dim=5000, output_dim=64, input_length=sequence_length),
    SimpleRNN(128, return_sequences=True),
    Dense(5000, activation="softmax")
])

model_one_to_many.compile(optimizer="adam", loss="sparse_categorical_crossentropy")

model_one_to_many.fit(X_gen, y_gen, epochs=10, batch_size=32)


Epoch 1/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 28s 167ms/step - loss: 8.5175
Epoch 2/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 165ms/step - loss: 8.4288
Epoch 3/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 164ms/step - loss: 8.0329
Epoch 4/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 165ms/step - loss: 7.5369
Epoch 5/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 164ms/step - loss: 7.0781
Epoch 6/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 166ms/step - loss: 6.6738
Epoch 7/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 166ms/step - loss: 6.3001
Epoch 8/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 26s 163ms/step - loss: 5.9667
Epoch 9/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 162ms/step - loss: 5.6445
Epoch 10/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 41s 165ms/step - loss: 5.3385
