In [ ]:
pip install faker


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 51.0 MB/s eta 0:00:00


In [ ]:
from faker import Faker
import random

In [ ]:
fake=Faker()

In [ ]:
texts=[]
labels=[]
for i in range(2000):
  if random.random()>0.5:
    texts.append(fake.text(max_nb_chars=50))
    labels.append(1)
  else:
    texts.append(fake.text(max_nb_chars=50))
    labels.append(0)

In [ ]:
train_texts=texts[:1600]
train_labels=labels[:1600]
test_texts=texts[1600:]
test_labels=labels[1600:]

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from gensim.models import Word2Vec
import numpy as np
from tensorflow.keras.utils import to_categorical

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(train_texts)

In [ ]:
word_index=tokenizer.word_index

In [ ]:
word_index

{'area': 1,
 'medical': 2,
 'begin': 3,
 'deal': 4,
 'debate': 5,
 'crime': 6,
 'election': 7,
 'sea': 8,
 'raise': 9,
 'above': 10,
 'that': 11,
 'professional': 12,
 'energy': 13,
 'young': 14,
 'its': 15,
 'turn': 16,
 'i': 17,
 'pm': 18,
 'song': 19,
 'wind': 20,
 'second': 21,
 'fall': 22,
 'one': 23,
 'bring': 24,
 'book': 25,
 'police': 26,
 'condition': 27,
 'allow': 28,
 'our': 29,
 'same': 30,
 'recently': 31,
 'sound': 32,
 'back': 33,
 'everyone': 34,
 'wait': 35,
 'successful': 36,
 'information': 37,
 'key': 38,
 'should': 39,
 'third': 40,
 'night': 41,
 'poor': 42,
 'else': 43,
 'team': 44,
 'wish': 45,
 'step': 46,
 'central': 47,
 'help': 48,
 'very': 49,
 'lay': 50,
 'little': 51,
 'data': 52,
 'give': 53,
 'house': 54,
 'we': 55,
 'nation': 56,
 'cost': 57,
 'offer': 58,
 'meet': 59,
 'shake': 60,
 'ok': 61,
 'kitchen': 62,
 'piece': 63,
 'top': 64,
 'far': 65,
 'suggest': 66,
 'better': 67,
 'picture': 68,
 'down': 69,
 'study': 70,
 'later': 71,
 'dog': 72,
 'beli

In [ ]:
max_sequence_length=50
train_sequences=tokenizer.texts_to_sequences(train_texts)
train_data=pad_sequences(train_sequences,maxlen=max_sequence_length)

In [ ]:
max_sequence_length

50

In [ ]:
train_padded=pad_sequences(train_sequences,maxlen=max_sequence_length)
train_padded=pad_sequences(train_sequences,maxlen=max_sequence_length,padding="post")

In [ ]:
train_padded

array([[654, 407, 158, ...,   0,   0,   0],
       [517, 408, 655, ...,   0,   0,   0],
       [518, 232, 656, ...,   0,   0,   0],
       ...,
       [305,  39,  76, ...,   0,   0,   0],
       [726, 392, 305, ...,   0,   0,   0],
       [481, 150, 606, ...,   0,   0,   0]], dtype=int32)

In [ ]:
train_labeds=to_categorical(train_labels)

In [ ]:
train_labels

[0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,


In [ ]:
test_labels=to_categorical(test_labels)

In [ ]:
w2v_model=Word2Vec(sentences=[text.split() for text in train_texts], vector_size=100)

In [ ]:
embedding_dim=100
embedding_matrix=np.zeros((len(word_index)+1,embedding_dim))

In [ ]:
embedding_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
for word, i in word_index.items():
  if word in w2v_model.wv:
    embedding_matrix[i]=w2v_model.wv[word]

In [ ]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00075676,  0.00099447,  0.00543852, ..., -0.0085754 ,
         0.00159658,  0.00598421],
       [-0.00848217,  0.00995871,  0.0001214 , ..., -0.00870155,
        -0.00197004, -0.00592708],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM, Dense

In [ ]:
model=Sequential([
    Embedding(input_dim=len(word_index)+1,
              output_dim=embedding_dim,
              weights=[embedding_matrix],
              input_length=max_sequence_length,
              trainable=False
              ),
    LSTM(128),
    Dense(2,activation="softmax")
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 7s 60ms/step - accuracy: 0.5047 - loss: 0.6934 - val_accuracy: 0.4875 - val_loss: 0.6948
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - accuracy: 0.5300 - loss: 0.6916 - val_accuracy: 0.4875 - val_loss: 0.6942
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.5066 - loss: 0.6933 - val_accuracy: 0.4875 - val_loss: 0.6949
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.5325 - loss: 0.6912 - val_accuracy: 0.4875 - val_loss: 0.6938
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.5276 - loss: 0.6917 - val_accuracy: 0.4875 - val_loss: 0.6938
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.5184 - loss: 0.6909 - val_accuracy: 0.5156 - val_loss: 0.6928
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.6034 - loss: 0.6768 - val_accuracy: 0.5312 - val_loss: 0.6952
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.5943 - loss: 0.6621 - val_accuracy: 0.5094 - v

In [ ]:
from tensorflow.keras.layers import Bidirectional

In [ ]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  Bidirectional(LSTM(128)),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.5185 - loss: 0.6927 - val_accuracy: 0.4875 - val_loss: 0.6937
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - accuracy: 0.5263 - loss: 0.6922 - val_accuracy: 0.4875 - val_loss: 0.6944
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.5144 - loss: 0.6927 - val_accuracy: 0.4875 - val_loss: 0.6940
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.5017 - loss: 0.6928 - val_accuracy: 0.4875 - val_loss: 0.6944
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5138 - loss: 0.6917 - val_accuracy: 0.4875 - val_loss: 0.6955
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.5159 - loss: 0.6904 - val_accuracy: 0.5281 - val_loss: 0.6936
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5830 - loss: 0.6810 - val_accuracy: 0.4844 - val_loss: 0.7293
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.5802 - loss: 0.6748 - val_accuracy: 0.4750 - v

In [ ]:
test_loss,test_accuracy=model.evaluate(test_padded,test_labels)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.5140 - loss: 0.7330


In [ ]:
test_accuracy

0.4950000047683716

In [ ]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  LSTM(128,return_sequences=True),
                  LSTM(64),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.5126 - loss: 0.6932 - val_accuracy: 0.5188 - val_loss: 0.6931
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5114 - loss: 0.6932 - val_accuracy: 0.4875 - val_loss: 0.6942
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.5186 - loss: 0.6928 - val_accuracy: 0.4875 - val_loss: 0.6944
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.5179 - loss: 0.6925 - val_accuracy: 0.4875 - val_loss: 0.6950
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.5189 - loss: 0.6925 - val_accuracy: 0.4875 - val_loss: 0.6941
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.5393 - loss: 0.6911 - val_accuracy: 0.4875 - val_loss: 0.6943
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.5124 - loss: 0.6927 - val_accuracy: 0.4875 - val_loss: 0.6940
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.5060 - loss: 0.6926 - val_accuracy: 0.4875 - v

In [ ]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  LSTM(128,dropout=0.2,recurrent_dropout=0.2),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
from tensorflow.keras.layers import GRU

In [ ]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  GRU(128,dropout=0.2,recurrent_dropout=0.2),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - accuracy: 0.5281 - loss: 0.6930 - val_accuracy: 0.4875 - val_loss: 0.6956
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5132 - loss: 0.6928 - val_accuracy: 0.4875 - val_loss: 0.6951
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.5409 - loss: 0.6908 - val_accuracy: 0.4875 - val_loss: 0.6936
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.5231 - loss: 0.6924 - val_accuracy: 0.4875 - val_loss: 0.6948
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.5202 - loss: 0.6921 - val_accuracy: 0.4875 - val_loss: 0.6944
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5241 - loss: 0.6921 - val_accuracy: 0.4875 - val_loss: 0.6943
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5277 - loss: 0.6919 - val_accuracy: 0.4875 - val_loss: 0.6948
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5221 - loss: 0.6919 - val_accuracy: 0.4875 - v