In [ ]:
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import nltk

# Download NLTK data files (only needed once)
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/True.csv')
df2=pd.read_csv('/content/drive/MyDrive/Fake.csv')

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer


In [ ]:
# Initialize the stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Define a preprocessing function
def preprocess_text(title):
    # Tokenization
    tokens = word_tokenize(title.lower())  # Convert to lowercase and tokenize
    # Stemming
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    # Lemmatization
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in stemmed_tokens]
    return " ".join(lemmatized_tokens)


In [ ]:
import nltk
nltk.download('punkt_tab')
  # Apply preprocessing to each data frame
df1['processed_text'] = df1['title'].apply(preprocess_text)
df2['processed_text'] = df2['title'].apply(preprocess_text)
# Display the first few rows of the processed data frames
print(df1.head())
print(df2.head())

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date                                     processed_text  
0  December 31, 2017   a u.s. budget fight loom , republican flip the...  
1  December 29, 2017   u.s. militari to accept transgend recruit on m...  
2  December 31, 2

##Stemming


In [ ]:
from nltk.stem import PorterStemmer

# Initialize the stemmer
stemmer = PorterStemmer()

# Apply stemming to a list of tokens
def stem_text(tokens):
    return "".join([stemmer.stem(token) for token in tokens])

# Apply stemming to tokenized text
df1['stemmed_text'] = df1['processed_text'].apply(stem_text)
df2['stemmed_text'] = df2['processed_text'].apply(stem_text)

# Display the stemmed data
print(df1[['processed_text', 'stemmed_text']])
print(df2[['processed_text', 'stemmed_text']])

                                          processed_text  \
0      a u.s. budget fight loom , republican flip the...   
1      u.s. militari to accept transgend recruit on m...   
2      senior u.s. republican senat : 'let mr. muelle...   
3      fbi russia probe help by australian diplomat t...   
4      trump want postal servic to charg 'much more '...   
...                                                  ...   
21412  'fulli commit ' nato back new u.s. approach on...   
21413   lexisnexi withdrew two product from chine market   
21414           minsk cultur hub becom haven from author   
21415  vatican upbeat on possibl of pope franci visit...   
21416  indonesia to buy $ 1.14 billion worth of russi...   

                                            stemmed_text  
0      a u.s. budget fight loom , republican flip the...  
1      u.s. militari to accept transgend recruit on m...  
2      senior u.s. republican senat : 'let mr. muelle...  
3      fbi russia probe help by australian 

##Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Apply lemmatization to a list of tokens
def lemmatize_text(tokens):
    return "".join([lemmatizer.lemmatize(token) for token in tokens])

# Apply lemmatization to tokenized text
df1['lemmatized_text'] = df1['processed_text'].apply(lemmatize_text)
df2['lemmatized_text'] = df2['processed_text'].apply(lemmatize_text)

# Display the lemmatized data
print(df1[['processed_text', 'lemmatized_text']].head())
print(df2[['processed_text', 'lemmatized_text']].head())

                                      processed_text  \
0  a u.s. budget fight loom , republican flip the...   
1  u.s. militari to accept transgend recruit on m...   
2  senior u.s. republican senat : 'let mr. muelle...   
3  fbi russia probe help by australian diplomat t...   
4  trump want postal servic to charg 'much more '...   

                                     lemmatized_text  
0  a u.s. budget fight loom , republican flip the...  
1  u.s. militari to accept transgend recruit on m...  
2  senior u.s. republican senat : 'let mr. muelle...  
3  fbi russia probe help by australian diplomat t...  
4  trump want postal servic to charg 'much more '...  
                                      processed_text  \
0  a u.s. budget fight loom , republican flip the...   
1  u.s. militari to accept transgend recruit on m...   
2  senior u.s. republican senat : 'let mr. muelle...   
3  fbi russia probe help by australian diplomat t...   
4  trump want postal servic to charg 'much more '... 

In [ ]:
print(df1[['processed_text', 'lemmatized_text']])
print(df2[['processed_text', 'lemmatized_text']])

                                          processed_text  \
0      a u.s. budget fight loom , republican flip the...   
1      u.s. militari to accept transgend recruit on m...   
2      senior u.s. republican senat : 'let mr. muelle...   
3      fbi russia probe help by australian diplomat t...   
4      trump want postal servic to charg 'much more '...   
...                                                  ...   
21412  'fulli commit ' nato back new u.s. approach on...   
21413   lexisnexi withdrew two product from chine market   
21414           minsk cultur hub becom haven from author   
21415  vatican upbeat on possibl of pope franci visit...   
21416  indonesia to buy $ 1.14 billion worth of russi...   

                                         lemmatized_text  
0      a u.s. budget fight loom , republican flip the...  
1      u.s. militari to accept transgend recruit on m...  
2      senior u.s. republican senat : 'let mr. muelle...  
3      fbi russia probe help by australian 

##Text Cleaning

In [ ]:
import pandas as pd
import re

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/True.csv')
df1=pd.read_csv('/content/drive/MyDrive/Fake.csv')
print(df1.head())
print(df2.head())

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
                                               title  \
0  As U.S. budget fight looms, Republicans

##POS

In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt')  # For tokenization
nltk.download('averaged_perceptron_tagger')  # For POS tagging

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
import pandas as pd

# Load the datasets (replace 'dataset1.csv' and 'dataset2.csv' with actual file names)
df1=pd.read_csv('/content/drive/MyDrive/True.csv')
df2=pd.read_csv('/content/drive/MyDrive/Fake.csv')
# Display the datasets
print("Dataset 1:")
print(df1.head())

print("\nDataset 2:")
print(df2.head())

Dataset 1:
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   

Dataset 2:
                                               title  \
0  As U.S. budget f

In [ ]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag

# Function to perform POS tagging
def pos_tagging(text):
    tokens = word_tokenize(text)  # Tokenize the text
    pos_tags = pos_tag(tokens)    # Perform POS tagging
    return pos_tags  # Return the POS tags

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
# Apply POS tagging to Dataset 1
df1['pos_tags'] = df1['title'].apply(pos_tagging)

# Apply POS tagging to Dataset 2
df2['pos_tags'] = df2['title'].apply(pos_tagging)

# Display the updated datasets
print("POS Tagged Dataset 1:")
print(df1.head())

print("\nPOS Tagged Dataset 2:")
print(df2.head())

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


POS Tagged Dataset 1:
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date                                           pos_tags  
0  December 31, 2017   [(As, IN), (U.S., NNP), (budget, NN), (fight, ...  
1  December 29, 2017   [(U.S., NNP), (military, JJ), (to, TO), (accep.

In [ ]:
# Save the updated datasets to new CSV files
df1.to_csv("pos_tagged_dataset1.csv", index=True)
df2.to_csv("pos_tagged_dataset2.csv", index=True)

print("POS-tagged datasets saved as 'pos_tagged_dataset1.csv' and 'pos_tagged_dataset2.csv'")

POS-tagged datasets saved as 'pos_tagged_dataset1.csv' and 'pos_tagged_dataset2.csv'


In [ ]:
# Reload the saved CSV files
df1_result = pd.read_csv("pos_tagged_dataset1.csv")
df2_result = pd.read_csv("pos_tagged_dataset2.csv")

# Display the first few rows of each dataset
print("POS-tagged Dataset 1:")
print(df1_result.head())

print("\nPOS-tagged Dataset 2:")
print(df2_result.head())

POS-tagged Dataset 1:
   Unnamed: 0                                              title  \
0           0  As U.S. budget fight looms, Republicans flip t...   
1           1  U.S. military to accept transgender recruits o...   
2           2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3           3  FBI Russia probe helped by Australian diplomat...   
4           4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date                                           pos_tags  
0  December 31, 2017   [('As', 'IN'), ('U.S.', 'NNP'), ('budget', 'NN... 

## NER Named Entity Recognition

In [ ]:
from nltk import word_tokenize
from nltk import pos_tag, ne_chunk
from nltk.tree import Tree

In [ ]:
# Function to perform Named Entity Recognition (NER)
def perform_ner(text):
    # Tokenize the text
    tokens = word_tokenize(text)
    # Perform POS tagging
    pos_tags = pos_tag(tokens)
    # Perform Named Entity Recognition
    named_entities = ne_chunk(pos_tags)

    # Extract named entities from the chunked structure
    entities = []
    for chunk in named_entities:
        if isinstance(chunk, Tree):  # If the chunk is a named entity
            entity_name = " ".join(c[0] for c in chunk)
            entity_type = chunk.label()  # Get the type of entity (e.g., PERSON, ORGANIZATION)
            entities.append((entity_name, entity_type))

    return entities

In [ ]:
# Load your dataset (update the filename if needed)
df1 = pd.read_csv('/content/drive/MyDrive/True.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Fake.csv')


In [ ]:
# Function to perform Named Entity Recognition (NER)
def perform_ner(text):
    # Tokenize, POS tagging, and chunking
    tokens = word_tokenize(text)
    pos_tags = pos_tag(tokens)
    named_entities = ne_chunk(pos_tags)

    # Extract named entities
    entities = []
    for chunk in named_entities:
        if isinstance(chunk, Tree):  # If the chunk is a named entity
            entity_name = " ".join(c[0] for c in chunk)  # Join the tokens
            entity_type = chunk.label()  # Entity type (e.g., PERSON, ORGANIZATION)
            entities.append((entity_name, entity_type))
    return entities

In [ ]:
print(df1.columns)
print(df2.columns)

Index(['title', 'text', 'subject', 'date'], dtype='object')
Index(['title', 'text', 'subject', 'date'], dtype='object')


In [ ]:
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [ ]:
!pip install svgling

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 3.0 MB/s eta 0:00:00


In [ ]:
words=nltk.word_tokenize(df1['title'][0])
print(words)

['As', 'U.S.', 'budget', 'fight', 'looms', ',', 'Republicans', 'flip', 'their', 'fiscal', 'script']


In [ ]:
words=nltk.word_tokenize(df1['text'][0])
print(words)

['WASHINGTON', '(', 'Reuters', ')', '-', 'The', 'head', 'of', 'a', 'conservative', 'Republican', 'faction', 'in', 'the', 'U.S.', 'Congress', ',', 'who', 'voted', 'this', 'month', 'for', 'a', 'huge', 'expansion', 'of', 'the', 'national', 'debt', 'to', 'pay', 'for', 'tax', 'cuts', ',', 'called', 'himself', 'a', '“', 'fiscal', 'conservative', '”', 'on', 'Sunday', 'and', 'urged', 'budget', 'restraint', 'in', '2018', '.', 'In', 'keeping', 'with', 'a', 'sharp', 'pivot', 'under', 'way', 'among', 'Republicans', ',', 'U.S.', 'Representative', 'Mark', 'Meadows', ',', 'speaking', 'on', 'CBS', '’', '“', 'Face', 'the', 'Nation', ',', '”', 'drew', 'a', 'hard', 'line', 'on', 'federal', 'spending', ',', 'which', 'lawmakers', 'are', 'bracing', 'to', 'do', 'battle', 'over', 'in', 'January', '.', 'When', 'they', 'return', 'from', 'the', 'holidays', 'on', 'Wednesday', ',', 'lawmakers', 'will', 'begin', 'trying', 'to', 'pass', 'a', 'federal', 'budget', 'in', 'a', 'fight', 'likely', 'to', 'be', 'linked', 't

In [ ]:
tag_elements=nltk.pos_tag(words)

In [ ]:
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [ ]:
import nltk
nltk.download('maxent_ne_chunker_tab')
nltk.ne_chunk(tag_elements)

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.


In [49]:
import nltk
from nltk import word_tokenize, pos_tag, ne_chunk

nltk.download('punkt')
nltk.download('maxent_ne_chunker')
nltk.download('words')

tokens = word_tokenize(df1['text'][0])
tags = pos_tag(tokens)

ner_tree = ne_chunk(tags)

print(ner_tree)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


(S
  (GPE WASHINGTON/NNP)
  (/(
  (ORGANIZATION Reuters/NNP)
  )/)
  -/:
  The/DT
  head/NN
  of/IN
  a/DT
  conservative/JJ
  (ORGANIZATION Republican/JJ)
  faction/NN
  in/IN
  the/DT
  (GPE U.S./NNP)
  (ORGANIZATION Congress/NNP)
  ,/,
  who/WP
  voted/VBD
  this/DT
  month/NN
  for/IN
  a/DT
  huge/JJ
  expansion/NN
  of/IN
  the/DT
  national/JJ
  debt/NN
  to/TO
  pay/VB
  for/IN
  tax/NN
  cuts/NNS
  ,/,
  called/VBD
  himself/PRP
  a/DT
  “/JJ
  fiscal/JJ
  conservative/JJ
  ”/NN
  on/IN
  Sunday/NNP
  and/CC
  urged/VBD
  budget/NN
  restraint/NN
  in/IN
  2018/CD
  ./.
  In/IN
  keeping/VBG
  with/IN
  a/DT
  sharp/JJ
  pivot/NN
  under/IN
  way/NN
  among/IN
  Republicans/NNPS
  ,/,
  (GPE U.S./NNP)
  Representative/NNP
  (PERSON Mark/NNP Meadows/NNP)
  ,/,
  speaking/VBG
  on/IN
  (ORGANIZATION CBS/NNP)
  ’/NNP
  “/NNP
  Face/NNP
  the/DT
  (ORGANIZATION Nation/NNP)
  ,/,
  ”/NNP
  drew/VBD
  a/DT
  hard/JJ
  line/NN
  on/IN
  federal/JJ
  spending/NN
  ,/,
  which/WDT
  la

In [51]:
# Install the required libraries
# !pip install nltk termcolor

import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
from termcolor import colored

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [50]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [52]:
nltk.download("maxent_ne_chunker_tab")

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


True

In [54]:
def visualize_entities(text):
    # Tokenize and tag the text
    tokens = word_tokenize(df1['text'][0])
    tagged_tokens = pos_tag(tokens)

    # Use ne_chunk to get named entities
    named_entities = ne_chunk(tagged_tokens)

    # Define colors for entity types
    entity_colors = {
        "PERSON": "green",
        "ORGANIZATION": "cyan",
        "GPE": "yellow",
        "LOCATION": "magenta",
        "DATE": "blue",
        "MONEY": "red",
    }

    # Parse and display entities with color
    for chunk in named_entities:
        if hasattr(chunk, 'label'):
            entity_type = chunk.label()
            entity_name = " ".join(c[0] for c in chunk)
            color = entity_colors.get(entity_type, "white")
            print(colored(f"{entity_name} ({entity_type})", color))
        else:
            # Print non-entity words normally
            print(chunk[0], end=" ")
    print()  # Add a newline at the end

# Test the function with a sample sentence

visualize_entities(df1['text'][0])


WASHINGTON (GPE)
( Reuters (ORGANIZATION)
) - The head of a conservative Republican (ORGANIZATION)
faction in the U.S. (GPE)
Congress (ORGANIZATION)
, who voted this month for a huge expansion of the national debt to pay for tax cuts , called himself a “ fiscal conservative ” on Sunday and urged budget restraint in 2018 . In keeping with a sharp pivot under way among Republicans , U.S. (GPE)
Representative Mark Meadows (PERSON)
, speaking on CBS (ORGANIZATION)
’ “ Face the Nation (ORGANIZATION)
, ” drew a hard line on federal spending , which lawmakers are bracing to do battle over in January . When they return from the holidays on Wednesday , lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues , such as immigration policy , even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress (ORGANIZATION)
. President Donald Trump (PERSON)
and his Republicans want a big budget increase

In [56]:
#
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")


doc = nlp(df1['text'][0])

displacy.render(doc, style="ent", jupyter=True)

##Create bag of Words

In [57]:
from sklearn.feature_extraction.text import CountVectorizer

In [58]:
cv=CountVectorizer(max_features=100,binary=True)

In [66]:
X=cv.fit_transform(df2['text']).toarray()

In [68]:
df2['text']=df2['text'][:2]

In [69]:
X

array([[1, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 1]])

In [70]:
df2['text']

0        WASHINGTON (Reuters) - The head of a conservat...
1        WASHINGTON (Reuters) - Transgender people will...
2                                                      NaN
3                                                      NaN
4                                                      NaN
                               ...                        
21412                                                  NaN
21413                                                  NaN
21414                                                  NaN
21415                                                  NaN
21416                                                  NaN
Name: text, Length: 21417, dtype: object

In [71]:
cv.get_feature_names_out()

array(['about', 'after', 'against', 'all', 'also', 'an', 'and', 'any',
       'are', 'as', 'at', 'be', 'been', 'before', 'between', 'but', 'by',
       'can', 'could', 'country', 'did', 'donald', 'during', 'election',
       'first', 'for', 'former', 'from', 'government', 'had', 'has',
       'have', 'he', 'his', 'house', 'if', 'in', 'including', 'into',
       'is', 'it', 'its', 'last', 'minister', 'more', 'national', 'new',
       'no', 'not', 'of', 'on', 'one', 'or', 'other', 'out', 'over',
       'people', 'president', 'republican', 'reuters', 'said', 'security',
       'since', 'some', 'state', 'statement', 'states', 'than', 'that',
       'the', 'their', 'there', 'they', 'this', 'thursday', 'time', 'to',
       'told', 'trump', 'tuesday', 'two', 'under', 'united', 'up', 'was',
       'washington', 'we', 'wednesday', 'week', 'were', 'what', 'when',
       'which', 'while', 'who', 'will', 'with', 'would', 'year', 'years'],
      dtype=object)

In [72]:
cv.vocabulary_

{'washington': 85,
 'reuters': 59,
 'the': 69,
 'of': 49,
 'republican': 58,
 'in': 36,
 'who': 94,
 'this': 73,
 'for': 25,
 'national': 45,
 'to': 76,
 'on': 50,
 'and': 6,
 'with': 96,
 'under': 81,
 'which': 92,
 'are': 8,
 'over': 55,
 'when': 91,
 'they': 72,
 'from': 27,
 'wednesday': 87,
 'will': 95,
 'be': 11,
 'other': 53,
 'as': 9,
 'election': 23,
 'president': 57,
 'donald': 21,
 'trump': 78,
 'his': 33,
 'while': 93,
 'also': 4,
 'that': 68,
 'has': 30,
 'been': 12,
 'we': 86,
 'by': 16,
 'about': 0,
 'but': 15,
 'house': 34,
 'said': 60,
 'not': 48,
 'government': 28,
 'is': 39,
 'out': 54,
 'people': 56,
 'he': 32,
 'was': 84,
 'their': 70,
 'years': 99,
 'it': 40,
 'would': 97,
 'united': 82,
 'states': 66,
 'one': 51,
 'more': 44,
 'than': 67,
 'or': 52,
 'have': 31,
 'some': 63,
 'country': 19,
 'told': 77,
 'did': 20,
 'an': 5,
 'after': 1,
 'first': 24,
 'time': 75,
 'two': 80,
 'last': 42,
 'week': 88,
 'before': 13,
 'had': 29,
 'were': 89,
 'statement': 65,
 'al

##TF-IDF

In [74]:
df1['text']=df1['text'][:3]

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [85]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(df1['text'][:3]).toarray()

In [81]:
df1['text'][:3]

0    WASHINGTON (Reuters) - The head of a conservat...
1    WASHINGTON (Reuters) - Transgender people will...
2    WASHINGTON (Reuters) - The special counsel inv...
Name: text, dtype: object

In [86]:
X

array([[0.03991302, 0.05139528, 0.        , 0.02660868, 0.        ,
        0.01330434, 0.21286945, 0.        , 0.        , 0.02660868,
        0.09313039, 0.        , 0.        , 0.07982604, 0.01713176,
        0.11263104, 0.02660868, 0.07982604, 0.        , 0.05139528,
        0.05139528, 0.        , 0.        , 0.06757862, 0.06757862,
        0.06757862, 0.05139528, 0.11263104, 0.        , 0.03426352,
        0.        , 0.01713176, 0.01330434, 0.03991302, 0.06757862,
        0.19956511, 0.02660868, 0.        , 0.        , 0.05321736,
        0.01330434, 0.02660868, 0.02660868, 0.10279057, 0.        ,
        0.25278247, 0.        , 0.05139528, 0.02660868, 0.01713176,
        0.01713176, 0.03426352, 0.        , 0.01713176, 0.09010483,
        0.01713176, 0.        , 0.03991302, 0.        , 0.17295643,
        0.17295643, 0.02660868, 0.08565881, 0.03426352, 0.06757862,
        0.        , 0.03426352, 0.02660868, 0.02660868, 0.11263104,
        0.06757862, 0.07982604, 0.13705409, 0.  

In [87]:
tfidf.vocabulary_

{'washington': 91,
 'the': 82,
 'of': 59,
 'conservative': 20,
 'republican': 71,
 'in': 45,
 'who': 96,
 'this': 85,
 'for': 35,
 'debt': 25,
 'to': 86,
 'tax': 79,
 'cuts': 24,
 'fiscal': 34,
 'on': 60,
 'and': 6,
 'budget': 15,
 '2018': 0,
 'with': 98,
 'way': 92,
 'republicans': 72,
 'representative': 70,
 'meadows': 54,
 'cbs': 19,
 'federal': 33,
 'spending': 78,
 'which': 94,
 'lawmakers': 51,
 'are': 9,
 'do': 29,
 'over': 63,
 'they': 84,
 'from': 36,
 'will': 97,
 'begin': 14,
 'be': 13,
 'other': 62,
 'as': 10,
 'policy': 67,
 'election': 31,
 'president': 68,
 'trump': 88,
 'his': 42,
 'want': 89,
 'military': 55,
 'while': 95,
 'democrats': 27,
 'defense': 26,
 'programs': 69,
 'that': 81,
 'administration': 3,
 'has': 39,
 'we': 93,
 'by': 17,
 'about': 1,
 'but': 16,
 'house': 43,
 'said': 75,
 'not': 57,
 'is': 47,
 'people': 66,
 'he': 41,
 'was': 90,
 'their': 83,
 'overhaul': 64,
 'expected': 32,
 'it': 48,
 'crowley': 23,
 'would': 99,
 'than': 80,
 'or': 61,
 'may'

##Word2Vec

In [88]:
!pip install gensim

In [89]:
from gensim.models import Word2Vec, KeyedVectors

In [90]:
import gensim.downloader as api
wv=api.load("word2vec-google-news-300")


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [91]:
vec_king=wv['king']

In [92]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [93]:
vec_king.shape

(300,)

In [94]:
wv.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [96]:
vec_cricket=wv['cricket']

In [97]:
vec_cricket

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [98]:
wv.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

##Naive Bayes Classifier

In [101]:
import pandas as pd

In [127]:
data={
"text":df2['title'][:20],
"label":[
        "real", "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real",
        "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real", "fake"
]}
df=pd.DataFrame(data)

In [128]:
df

text label
0   As U.S. budget fight looms, Republicans flip t...  real
1   U.S. military to accept transgender recruits o...  fake
2   Senior U.S. Republican senator: 'Let Mr. Muell...  real
3   FBI Russia probe helped by Australian diplomat...  real
4   Trump wants Postal Service to charge 'much mor...  fake
5   White House, Congress prepare for talks on spe...  real
6   Trump says Russia probe will be fair, but time...  fake
7   Factbox: Trump on Twitter (Dec 29) - Approval ...  real
8          Trump on Twitter (Dec 28) - Global Warming  fake
9   Alabama official to certify Senator-elect Jone...  real
10  Jones certified U.S. Senate winner despite Moo...  fake
11  New York governor questions the constitutional...  real
12  Factbox: Trump on Twitter (Dec 28) - Vanity Fa...  real
13     Trump on Twitter (Dec 27) - Trump, Iraq, Syria  fake
14  Man says he delivered manure to Mnuchin to pro...  real
15  Virginia officials postpone lottery drawing to...  fake
16  U.S. lawmakers question businessman at 2016 Tr...  real
17  Trump on Twitter (Dec 26) - Hillary Clinton, T...  fake
18  U.S. appeals court rejects challenge to Trump ...  real
19  Treasury Secretary Mnuchin was sent gift-wrapp...  fake

In [111]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [129]:
df['label']=df['label'].map({"fake":0,"real":1})
df['label']

0     1
1     0
2     1
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
Name: label, dtype: int64

In [130]:
df['label'].value_counts()

label
1    11
0     9
Name: count, dtype: int64

In [131]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [132]:
lemmatizer=WordNetLemmatizer()

In [133]:
stop_words=set(stopwords.words("english"))

In [134]:
def preprocess_text(text):
  text=text.lower()
  tokens=text.split()
  tokens=[word for word in tokens if word not in stop_words]
  tokens=[lemmatizer.lemmatize(word) for word in tokens]
  return " ".join(tokens)
df['text']=df['text'].apply(preprocess_text)

In [135]:
df

text  label
0   u.s. budget fight looms, republican flip fisca...      1
1   u.s. military accept transgender recruit monda...      0
2   senior u.s. republican senator: 'let mr. muell...      1
3   fbi russia probe helped australian diplomat ti...      1
4   trump want postal service charge 'much more' a...      0
5   white house, congress prepare talk spending, i...      1
6   trump say russia probe fair, timeline unclear:...      0
7   factbox: trump twitter (dec 29) - approval rat...      1
8             trump twitter (dec 28) - global warming      0
9   alabama official certify senator-elect jones t...      1
10  jones certified u.s. senate winner despite moo...      0
11  new york governor question constitutionality f...      1
12  factbox: trump twitter (dec 28) - vanity fair,...      1
13        trump twitter (dec 27) - trump, iraq, syria      0
14  man say delivered manure mnuchin protest new u...      1
15  virginia official postpone lottery drawing dec...      0
16  u.s. lawmaker question businessman 2016 trump ...      1
17  trump twitter (dec 26) - hillary clinton, tax ...      0
18  u.s. appeal court reject challenge trump voter...      1
19  treasury secretary mnuchin sent gift-wrapped b...      0

In [136]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['label'],test_size=0.1,random_state=42)


In [137]:
print(X_train.shape)

(18,)


In [138]:
X_test.shape

(2,)

In [139]:
y_train.value_counts()

label
1    10
0     8
Name: count, dtype: int64

In [140]:
y_test.value_counts()

label
1    1
0    1
Name: count, dtype: int64

In [141]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()


In [142]:
X_train_vectorized=vectorizer.fit(X_train)

In [143]:
X_train_vectorized=vectorizer.transform(X_train)

In [144]:
X_test_vectorized=vectorizer.transform(X_test)

In [145]:
from sklearn.naive_bayes import MultinomialNB
nb_model=MultinomialNB()

In [146]:
nb_model.fit(X_train_vectorized,y_train)

MultinomialNB()

In [147]:
y_train_pred=nb_model.predict(X_train_vectorized)

In [148]:
list(y_train)

[0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0]

In [149]:
from sklearn.metrics import accuracy_score,classification_report

In [150]:
accuracy_score(y_train,y_train_pred)

1.0

In [151]:
y_test_pred=nb_model.predict(X_test_vectorized)

In [152]:
accuracy_score(y_test,y_test_pred)

0.5

In [153]:
y_test

0     1
17    0
Name: label, dtype: int64

In [154]:
y_test_pred

array([1, 1])

In [155]:
report=classification_report(y_test,y_test_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


##SVM

In [156]:
import pandas as pd
data={
"text":df2['title'][:20],
"label":[
        "real", "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real",
        "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real", "fake"
]}
df=pd.DataFrame(data)

In [157]:
df

text label
0   As U.S. budget fight looms, Republicans flip t...  real
1   U.S. military to accept transgender recruits o...  fake
2   Senior U.S. Republican senator: 'Let Mr. Muell...  real
3   FBI Russia probe helped by Australian diplomat...  real
4   Trump wants Postal Service to charge 'much mor...  fake
5   White House, Congress prepare for talks on spe...  real
6   Trump says Russia probe will be fair, but time...  fake
7   Factbox: Trump on Twitter (Dec 29) - Approval ...  real
8          Trump on Twitter (Dec 28) - Global Warming  fake
9   Alabama official to certify Senator-elect Jone...  real
10  Jones certified U.S. Senate winner despite Moo...  fake
11  New York governor questions the constitutional...  real
12  Factbox: Trump on Twitter (Dec 28) - Vanity Fa...  real
13     Trump on Twitter (Dec 27) - Trump, Iraq, Syria  fake
14  Man says he delivered manure to Mnuchin to pro...  real
15  Virginia officials postpone lottery drawing to...  fake
16  U.S. lawmakers question businessman at 2016 Tr...  real
17  Trump on Twitter (Dec 26) - Hillary Clinton, T...  fake
18  U.S. appeals court rejects challenge to Trump ...  real
19  Treasury Secretary Mnuchin was sent gift-wrapp...  fake

In [158]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [159]:
df['label']=df['label'].map({"fake":0,"real":1})
df['label']

0     1
1     0
2     1
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
Name: label, dtype: int64

In [160]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [161]:
lemmatizer=WordNetLemmatizer()

In [162]:
stop_words=set(stopwords.words("english"))

In [163]:
def preprocess_text(text):
  text=text.lower()
  tokens=text.split()
  tokens=[word for word in tokens if word not in stop_words]
  tokens=[lemmatizer.lemmatize(word) for word in tokens]
  return " ".join(tokens)
df['text']=df['text'].apply(preprocess_text)

In [164]:
df

text  label
0   u.s. budget fight looms, republican flip fisca...      1
1   u.s. military accept transgender recruit monda...      0
2   senior u.s. republican senator: 'let mr. muell...      1
3   fbi russia probe helped australian diplomat ti...      1
4   trump want postal service charge 'much more' a...      0
5   white house, congress prepare talk spending, i...      1
6   trump say russia probe fair, timeline unclear:...      0
7   factbox: trump twitter (dec 29) - approval rat...      1
8             trump twitter (dec 28) - global warming      0
9   alabama official certify senator-elect jones t...      1
10  jones certified u.s. senate winner despite moo...      0
11  new york governor question constitutionality f...      1
12  factbox: trump twitter (dec 28) - vanity fair,...      1
13        trump twitter (dec 27) - trump, iraq, syria      0
14  man say delivered manure mnuchin protest new u...      1
15  virginia official postpone lottery drawing dec...      0
16  u.s. lawmaker question businessman 2016 trump ...      1
17  trump twitter (dec 26) - hillary clinton, tax ...      0
18  u.s. appeal court reject challenge trump voter...      1
19  treasury secretary mnuchin sent gift-wrapped b...      0

In [165]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['label'],test_size=0.2,random_state=42)


In [166]:
X_train.shape,X_test.shape

((16,), (4,))

In [167]:
from sklearn.feature_extraction.text import CountVectorizer

In [168]:
vectorizer=CountVectorizer()

In [169]:
X_train_vectorized=vectorizer.fit_transform(X_train)

In [170]:
X_test_vectorized=vectorizer.transform(X_test)

In [171]:
from sklearn.svm import SVC

In [172]:
svm_model=SVC(kernel="linear",random_state=42)

In [173]:
svm_model.fit(X_train_vectorized,y_train)

SVC(kernel='linear', random_state=42)

In [174]:
y_train_pred=svm_model.predict(X_train_vectorized)

In [175]:
from sklearn.metrics import accuracy_score,classification_report

In [176]:
accuracy_score(y_train,y_train_pred)

1.0

In [177]:
y_test_pred=svm_model.predict(X_test_vectorized)

In [178]:
accuracy_score(y_test,y_test_pred)

0.25

In [179]:
y_test,y_test_pred

(0     1
 17    0
 15    0
 1     0
 Name: label, dtype: int64,
 array([1, 1, 1, 1]))

In [180]:
report=classification_report(y_test,y_test_pred)
print(report)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.25      1.00      0.40         1

    accuracy                           0.25         4
   macro avg       0.12      0.50      0.20         4
weighted avg       0.06      0.25      0.10         4



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


##Hyperparameter tuning


In [181]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
param_grid={

            "C":[0.1,0.3,0.5,1,10],
            "kernel":["linear","rbf"],
            "gamma":['scale',"auto"]
}

svm_model=SVC(random_state=42)

In [182]:
grid_search=GridSearchCV(svm_model,param_grid,cv=5,scoring="accuracy")

In [183]:
grid_search.fit(X_train_vectorized,y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=42),
             param_grid={'C': [0.1, 0.3, 0.5, 1, 10],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [184]:
grid_search.best_params_

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}

In [185]:
grid_search.best_score_

0.6333333333333332

In [186]:
best_model=grid_search.best_estimator_

In [187]:
y_pred=best_model.predict(X_test_vectorized)

In [188]:
report=classification_report(y_test,y_test_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.25      1.00      0.40         1

    accuracy                           0.25         4
   macro avg       0.12      0.50      0.20         4
weighted avg       0.06      0.25      0.10         4



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [189]:
accuracy_score(y_test,y_test_pred)

0.25

##ANN

In [223]:
import pandas as pd
data={
"text":df2['title'][:20],
"label":[
        "real", "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real",
        "fake", "real", "real", "fake", "real", "fake", "real", "fake", "real", "fake"
]}
df=pd.DataFrame(data)

In [192]:
df=pd.DataFrame(data)

In [193]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [194]:
tfidf=TfidfVectorizer(max_features=50)

In [195]:
from sklearn.model_selection import train_test_split

In [199]:
X=tfidf.fit_transform(df['text']).toarray()
y=df['label']

In [200]:
from tensorflow.keras.models import Sequential

In [201]:
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

In [202]:
model=Sequential([Dense(64,activation='relu',input_shape=(X.shape[1],)),
                  Dropout(0.5),
                  Dense(32,activation="relu"),
                  Dense(1,activation="sigmoid")

                  ])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [203]:
model.compile(optimizer=Adam(learning_rate=0.001),
              loss=BinaryCrossentropy(),
              metrics=['accuracy'])

In [207]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

# Example dataset (replace with actual data)
import numpy as np
X = np.random.rand(100, 10)  # 100 samples, 10 features
y = np.random.randint(2, size=(100, 1))  # 100 binary labels

# Define the model
model = Sequential([
    Dense(32, activation='relu', input_shape=(X.shape[1],)),  # Input layer
    Dense(16, activation='relu'),  # Hidden layer
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001),
              loss=BinaryCrossentropy(),
              metrics=['accuracy'])

# Train the model
model.fit(X,y,epochs=10,batch_size=8)

Epoch 1/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4247 - loss: 0.6954
Epoch 2/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4869 - loss: 0.6873 
Epoch 3/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6065 - loss: 0.6821  
Epoch 4/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5625 - loss: 0.6810 
Epoch 5/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5627 - loss: 0.6879 
Epoch 6/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6761 - loss: 0.6763 
Epoch 7/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6066 - loss: 0.6787  
Epoch 8/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6785 
Epoch 9/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6213 - loss: 0.6775  
Epoch 10/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6744 - loss: 0.6683  


In [208]:
loss,accuracy=model.evaluate(X,y)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6683 - loss: 0.6669  


In [209]:
loss,accuracy

(0.6696841716766357, 0.6499999761581421)

In [210]:
model.predict(X)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[0.49530062],
       [0.55566204],
       [0.5222372 ],
       [0.47076756],
       [0.5206695 ],
       [0.47126397],
       [0.5286525 ],
       [0.4646715 ],
       [0.47785208],
       [0.52008015],
       [0.44802612],
       [0.5253701 ],
       [0.4440726 ],
       [0.5004606 ],
       [0.54073995],
       [0.5391268 ],
       [0.5596347 ],
       [0.51656955],
       [0.5260817 ],
       [0.5793453 ],
       [0.51601034],
       [0.52181005],
       [0.49717608],
       [0.547605  ],
       [0.56396204],
       [0.6104749 ],
       [0.5441149 ],
       [0.5746969 ],
       [0.56457484],
       [0.56712854],
       [0.54039127],
       [0.4527975 ],
       [0.5272582 ],
       [0.56596273],
       [0.55117667],
       [0.55083793],
       [0.5745554 ],
       [0.47854388],
       [0.42939317],
       [0.548197  ],
       [0.49714422],
       [0.56361157],
       [0.5101448 ],
       [0.51901025],
       [0.5765011 ],
       [0.54894996],
       [0.4306775 ],
       [0.533

In [211]:
y

array([[0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
    

##RNN

In [212]:
!pip install faker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 16.8 MB/s eta 0:00:00


In [213]:
from faker import Faker

In [214]:
import numpy as np

In [215]:
fake=Faker()
Faker.seed(42)

In [217]:
def generate_text_labels(num_samples=5000):
    text=[fake.sentence(nb_words=10) for i in range(num_samples)]
    labels=np.random.randint(0,2,num_samples)
    return text,labels

In [218]:
texts,labels=generate_text_labels()

In [224]:
import pandas as pd
data={
"texts":df2['title'][:20000],}
df=pd.DataFrame(data)

In [226]:
texts

['Agent every development say quality throughout beautiful.',
 'All behavior discussion own night respond red information last everything thank.',
 'Recently future choice whatever from behavior benefit suggest.',
 'Enough analysis least by two bad fall pick those gun court attorney product.',
 'World talk term herself law street class great prove.',
 'Participant commercial rock clear here writer.',
 'Detail food shoulder argue start source husband at tree note responsibility defense material.',
 'Central cause seat much section investment on gun young catch management.',
 'Technology check civil quite others his.',
 'You more wife team activity result race Mr environment political born itself law.',
 'Will seven medical blood personal success medical current hear.',
 'Much single morning a food affect upon these.',
 'Dream drive note bad rule staff within mouth call.',
 'Water close month parent who up sense ready require human public health.',
 'Later easy ask again network open acc

In [227]:
labels

array([1, 1, 1, ..., 0, 1, 1])

In [228]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [229]:
tokenizer=Tokenizer(num_words=10000)

In [230]:
tokenizer.fit_on_texts(texts)

In [231]:
sequences=tokenizer.texts_to_sequences(texts)

In [232]:
sequences

[[738, 228, 739, 821, 378, 191, 650],
 [330, 29, 379, 487, 192, 782, 229, 740, 282, 42, 822],
 [230, 30, 331, 117, 741, 29, 231, 22],
 [651, 91, 283, 590, 284, 118, 285, 652, 119, 120, 783, 784, 332],
 [424, 193, 23, 425, 16, 43, 785, 426, 742],
 [333, 956, 286, 121, 334, 743],
 [957, 696, 92, 335, 653, 75, 122, 427, 428, 76, 591, 232, 194],
 [592, 233, 915, 697, 336, 593, 698, 120, 429, 123, 699],
 [744, 870, 700, 195, 337, 338],
 [5, 60, 44, 594, 339, 234, 488, 287, 288, 31, 654, 289, 16],
 [538, 430, 340, 61, 290, 235, 340, 952, 786],
 [697, 45, 964, 431, 696, 871, 936, 432],
 [380, 291, 76, 118, 823, 787, 152, 539, 341],
 [46, 655, 489, 32, 656, 196, 24, 197, 342, 788, 153, 236],
 [490, 491, 492, 62, 595, 824, 343, 745, 237, 2, 330, 596],
 [540, 292, 238, 433, 825, 124, 344, 541, 542, 77, 434, 381],
 [154, 78, 8, 701, 493, 382, 286, 345, 597, 783, 890],
 [33, 42, 63, 746, 383, 744, 93],
 [543, 155, 916, 29, 747, 702],
 [494, 657, 122, 198, 598, 424, 435, 541, 293, 294, 117],
 [332,

In [233]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [234]:
padded_sequences=pad_sequences(sequences,maxlen=20)

In [235]:
padded_sequences[0:2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        738, 228, 739, 821, 378, 191, 650],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 330,  29, 379, 487,
        192, 782, 229, 740, 282,  42, 822]], dtype=int32)

In [236]:
train_size=int(0.8*len(padded_sequences))

In [237]:
X_train,X_test=padded_sequences[:train_size],padded_sequences[train_size:]

In [238]:
y_train,y_test=labels[:train_size],labels[train_size:]

In [239]:
X_train.shape

(4000, 20)

In [240]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN,Dense

In [241]:
model_one_to_one=Sequential([
                             Embedding(input_dim=5000,output_dim=64,input_length=20),
                             SimpleRNN(64,return_sequences=False),
                             Dense(1,activation="softmax")
                             ])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [242]:
model_one_to_one.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [243]:
model_one_to_one.fit(X_train,y_train,epochs=5,batch_size=32,validation_split=0.2)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


100/100 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.5234 - loss: 0.6958 - val_accuracy: 0.4875 - val_loss: 0.7007
Epoch 2/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.4989 - loss: 0.5752 - val_accuracy: 0.4875 - val_loss: 0.8069
Epoch 3/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.4956 - loss: 0.2550 - val_accuracy: 0.4875 - val_loss: 1.1659
Epoch 4/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5098 - loss: 0.0953 - val_accuracy: 0.4875 - val_loss: 1.7275
Epoch 5/5
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5000 - loss: 0.0236 - val_accuracy: 0.4875 - val_loss: 2.0725


In [244]:
model_one_to_one.predict(X_test)

32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step


/usr/local/lib/python3.10/dist-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


array([[0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.999

In [245]:
model_one_to_many=Sequential([
                             Embedding(input_dim=5000,output_dim=64,input_length=1),
                             SimpleRNN(64,return_sequences=True),
                             Dense(5000,activation="softmax")
                             ])

In [246]:
X_gen=np.random.randint(1,5000,size=(5000,1))
y_gen=np.random.randint(1,5000,size=(5000,10))

In [247]:
X_gen.shape

(5000, 1)

In [248]:
y_gen.shape


(5000, 10)

In [249]:
y_gen

array([[4066,  972,  509, ..., 1750, 4521,  542],
       [4667, 1154, 2777, ..., 1539,  980, 2011],
       [4158, 2633, 1047, ...,  100, 3235, 4679],
       ...,
       [ 826, 2473, 1565, ...,  851, 4251, 3547],
       [3639, 4304, 4015, ..., 3451, 3216, 4968],
       [4322, 4424, 3012, ..., 4788, 3778, 2014]])

In [255]:
sequence_length = 10
X_gen = np.random.randint(1, 5000, size=(5000, sequence_length))
y_gen = np.random.randint(1, 5000, size=(5000, sequence_length))

model_one_to_many = Sequential([
    Embedding(input_dim=5000, output_dim=64, input_length=sequence_length),
    SimpleRNN(128, return_sequences=True),
    Dense(5000, activation="softmax")
])

model_one_to_many.compile(optimizer="adam", loss="sparse_categorical_crossentropy")

model_one_to_many.fit(X_gen, y_gen, epochs=10, batch_size=32)


Epoch 1/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 32s 181ms/step - loss: 8.5174
Epoch 2/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 26s 165ms/step - loss: 8.4304
Epoch 3/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 29s 184ms/step - loss: 8.0359
Epoch 4/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 38s 167ms/step - loss: 7.5415
Epoch 5/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 43s 177ms/step - loss: 7.0830
Epoch 6/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 28s 181ms/step - loss: 6.6687
Epoch 7/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 26s 162ms/step - loss: 6.3021
Epoch 8/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 43s 172ms/step - loss: 5.9537
Epoch 9/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 28s 182ms/step - loss: 5.6193
Epoch 10/10
157/157 ━━━━━━━━━━━━━━━━━━━━ 26s 165ms/step - loss: 5.3318


##LSTM

In [256]:
pip install faker

In [257]:
from faker import Faker
import random

In [258]:
fake=Faker()

In [259]:
texts=[]
labels=[]
for i in range(2000):
  if random.random()>0.5:
    texts.append(fake.text(max_nb_chars=50))
    labels.append(1)
  else:
    texts.append(fake.text(max_nb_chars=50))
    labels.append(0)


In [260]:
train_texts=texts[:1600]
test_texts=texts[1600:]
train_labels=labels[:1600]
test_labels=labels[1600:]

In [261]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from gensim.models import Word2Vec
import numpy as np
from tensorflow.keras.utils import to_categorical

In [262]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(train_texts)

In [263]:
train_sequences=tokenizer.texts_to_sequences(train_texts)
test_sequences=tokenizer.texts_to_sequences(test_texts)

In [264]:
word_index=tokenizer.word_index

In [265]:
word_index

{'ok': 1,
 'news': 2,
 'stuff': 3,
 'during': 4,
 'adult': 5,
 'from': 6,
 'assume': 7,
 'turn': 8,
 'station': 9,
 'blue': 10,
 'toward': 11,
 'anyone': 12,
 'upon': 13,
 'next': 14,
 'but': 15,
 'best': 16,
 'chance': 17,
 'each': 18,
 'about': 19,
 'star': 20,
 'tax': 21,
 'really': 22,
 'heart': 23,
 'memory': 24,
 'key': 25,
 'soldier': 26,
 'go': 27,
 'final': 28,
 'road': 29,
 'find': 30,
 'wide': 31,
 'onto': 32,
 'summer': 33,
 'keep': 34,
 'run': 35,
 'argue': 36,
 'say': 37,
 'feel': 38,
 'wish': 39,
 'sort': 40,
 'east': 41,
 'present': 42,
 'over': 43,
 'as': 44,
 'mean': 45,
 'up': 46,
 'reach': 47,
 'see': 48,
 'write': 49,
 'let': 50,
 'city': 51,
 'test': 52,
 'hundred': 53,
 'sit': 54,
 'act': 55,
 'another': 56,
 'maybe': 57,
 'line': 58,
 'step': 59,
 'serious': 60,
 'trial': 61,
 'laugh': 62,
 'listen': 63,
 'fine': 64,
 'focus': 65,
 'hot': 66,
 'agent': 67,
 'spend': 68,
 'task': 69,
 'because': 70,
 'my': 71,
 'usually': 72,
 'read': 73,
 'current': 74,
 'real':

In [266]:
max_sequence_length=max(len(seq) for seq in train_sequences)

In [267]:
max_sequence_length

10

In [268]:
train_padded=pad_sequences(train_sequences,maxlen=max_sequence_length,padding="post")
test_padded=pad_sequences(test_sequences,maxlen=max_sequence_length,padding="post")

In [269]:
train_padded

array([[413, 127, 542, ...,   0,   0,   0],
       [200, 414, 201, ...,   0,   0,   0],
       [ 26, 544, 302, ...,   0,   0,   0],
       ...,
       [123, 105, 905, ...,   0,   0,   0],
       [144, 335, 211, ...,   0,   0,   0],
       [650, 816, 319, ...,   0,   0,   0]], dtype=int32)

In [270]:
train_labels=to_categorical(train_labels)

In [271]:
train_labels

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [272]:
test_labels=to_categorical(test_labels)

In [273]:
w2v_model=Word2Vec(sentences=[text.split() for text in train_texts], vector_size=100)

In [274]:
embedding_dim=100
embedding_matrix=np.zeros((len(word_index)+1,embedding_dim))

In [275]:
embedding_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [276]:
for word, i in word_index.items():
  if word in w2v_model.wv:
    embedding_matrix[i]=w2v_model.wv[word]

In [277]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00120831, -0.00188889, -0.0016321 , ...,  0.00069408,
        -0.00820131, -0.0049158 ],
       [ 0.00477591,  0.00678351, -0.00792454, ...,  0.00042261,
        -0.00538835, -0.00603175],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [278]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM, Dense

In [279]:
model=Sequential([
    Embedding(input_dim=len(word_index)+1,
              output_dim=embedding_dim,
              weights=[embedding_matrix],
              input_length=max_sequence_length,
              trainable=False
              ),
    LSTM(128),
    Dense(2,activation="softmax")
])


In [280]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [281]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - accuracy: 0.5078 - loss: 0.6934 - val_accuracy: 0.4875 - val_loss: 0.6934
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.4874 - loss: 0.6935 - val_accuracy: 0.4875 - val_loss: 0.6938
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5208 - loss: 0.6925 - val_accuracy: 0.4875 - val_loss: 0.6935
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5073 - loss: 0.6930 - val_accuracy: 0.4875 - val_loss: 0.6937
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.4952 - loss: 0.6934 - val_accuracy: 0.4875 - val_loss: 0.6939
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5314 - loss: 0.6913 - val_accuracy: 0.4938 - val_loss: 0.6936
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.5113 - loss: 0.6924 - val_accuracy: 0.4875 - val_loss: 0.6972
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.5083 - loss: 0.6925 - val_accuracy: 0.5125 - v

In [282]:
test_loss,test_accuracy=model.evaluate(test_padded,test_labels)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4941 - loss: 0.7218


In [283]:
test_accuracy

0.5

###Bidirectional LSTM

In [284]:
from tensorflow.keras.layers import Bidirectional

In [285]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  Bidirectional(LSTM(128)),
                  Dense(2,activation="softmax")

])

In [286]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [287]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.5127 - loss: 0.6943 - val_accuracy: 0.4781 - val_loss: 0.6933
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5182 - loss: 0.6930 - val_accuracy: 0.4656 - val_loss: 0.6933
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - accuracy: 0.5164 - loss: 0.6928 - val_accuracy: 0.4875 - val_loss: 0.6937
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - accuracy: 0.5180 - loss: 0.6924 - val_accuracy: 0.4938 - val_loss: 0.6938
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5254 - loss: 0.6922 - val_accuracy: 0.4875 - val_loss: 0.6945
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.5131 - loss: 0.6917 - val_accuracy: 0.4812 - val_loss: 0.6950
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.5775 - loss: 0.6848 - val_accuracy: 0.4781 - val_loss: 0.6939
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 60ms/step - accuracy: 0.5666 - loss: 0.6844 - val_accuracy: 0.5125 - v

In [288]:
test_loss,test_accuracy=model.evaluate(test_padded,test_labels)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.4643 - loss: 0.7206


In [289]:
test_accuracy

0.47999998927116394

##Stacked LSTM

In [290]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  LSTM(128,return_sequences=True),
                  LSTM(64),
                  Dense(2,activation="softmax")

])

In [291]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [292]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 20s 147ms/step - accuracy: 0.4975 - loss: 0.6937 - val_accuracy: 0.5125 - val_loss: 0.6931
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 7s 62ms/step - accuracy: 0.5035 - loss: 0.6932 - val_accuracy: 0.4875 - val_loss: 0.6932
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - accuracy: 0.4978 - loss: 0.6933 - val_accuracy: 0.4875 - val_loss: 0.6933
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 85ms/step - accuracy: 0.4924 - loss: 0.6932 - val_accuracy: 0.4875 - val_loss: 0.6938
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.5214 - loss: 0.6926 - val_accuracy: 0.5156 - val_loss: 0.6931
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.5203 - loss: 0.6926 - val_accuracy: 0.4875 - val_loss: 0.6947
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.5110 - loss: 0.6912 - val_accuracy: 0.4469 - val_loss: 0.7040
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.5156 -

##LSTM Dropout

In [293]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  LSTM(128,dropout=0.2,recurrent_dropout=0.2),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## GRU

In [294]:
from tensorflow.keras.layers import GRU

In [295]:
model=Sequential([Embedding(input_dim=len(word_index)+1,
                            output_dim=embedding_dim,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length,
                            trainable=False
                            ),
                  GRU(128,dropout=0.2,recurrent_dropout=0.2),
                  Dense(2,activation="softmax")

])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [296]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [297]:
model.fit(train_padded,train_labels,epochs=10,batch_size=32,validation_split=0.2)

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.4753 - loss: 0.6939 - val_accuracy: 0.5125 - val_loss: 0.6930
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.4929 - loss: 0.6934 - val_accuracy: 0.4875 - val_loss: 0.6932
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5122 - loss: 0.6937 - val_accuracy: 0.4875 - val_loss: 0.6935
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5220 - loss: 0.6927 - val_accuracy: 0.4875 - val_loss: 0.6932
Epoch 5/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.4950 - loss: 0.6934 - val_accuracy: 0.4875 - val_loss: 0.6935
Epoch 6/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5063 - loss: 0.6931 - val_accuracy: 0.4906 - val_loss: 0.6932
Epoch 7/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.4940 - loss: 0.6932 - val_accuracy: 0.4875 - val_loss: 0.6934
Epoch 8/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5082 - loss: 0.6929 - val_accuracy: 0.4875 - v

In [299]:
test_accuracy

0.47999998927116394